# Generated by Django 3.2.4 on 2021-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210615_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='products/thumbnail'),
        ),
    ]
